version: '3.8'

services:
  # Servicio del backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: resumenes-ia-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - backend_db:/app/db
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Servicio del frontend con Apache
  frontend:
    image: httpd:2.4-alpine
    container_name: resumenes-ia-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_node_modules:
  backend_db: